# Generated by Django 2.2.12 on 2020-04-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalpayment',
            name='payment_day',
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='payment_date',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
