# Generated by Django 2.2.12 on 2020-04-15 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0003_auto_20200415_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
